//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarreraMatriculada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarreraMatriculada()
        {
            this.Titulo = new HashSet<Titulo>();
        }
    
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string ResolucionHabilitante { get; set; }
        public string ResolucionCierre { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public byte TipoEstadoProfesionID { get; set; }
    
        public virtual TipoEstadoProfesion TipoEstadoProfesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Titulo> Titulo { get; set; }
    }
}
