//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horarios()
        {
            this.HorariosPorEspecialidadPorCentroDeSalud = new HashSet<HorariosPorEspecialidadPorCentroDeSalud>();
            this.HorariosPorEspecialidadPorCentroDeSalud1 = new HashSet<HorariosPorEspecialidadPorCentroDeSalud>();
        }
    
        public short ID { get; set; }
        public string Hora { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorariosPorEspecialidadPorCentroDeSalud> HorariosPorEspecialidadPorCentroDeSalud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorariosPorEspecialidadPorCentroDeSalud> HorariosPorEspecialidadPorCentroDeSalud1 { get; set; }
    }
}
