//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaColectivoPorCentroDeSalud
    {
        public int ID { get; set; }
        public short LineaColectivoID { get; set; }
        public short CentroDeSaludID { get; set; }
        public bool Activo { get; set; }
    
        public virtual CentroDeSalud CentroDeSalud { get; set; }
        public virtual LineaColectivo LineaColectivo { get; set; }
    }
}
