//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesional
    {
        public int ID { get; set; }
        public int PersonaId { get; set; }
        public Nullable<int> SisaId { get; set; }
        public Nullable<System.DateTime> FechaInscripionSisa { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public bool ActualizadoSisa { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
