//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Matricula = new HashSet<Matricula>();
            this.Profesional = new HashSet<Profesional>();
        }
    
        public int ID { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public byte TipodniID { get; set; }
        public string NroDocumento { get; set; }
        public Nullable<byte> EstadoCivilID { get; set; }
        public Nullable<byte> SexoID { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<short> LocalidadID { get; set; }
        public string CodigoPostal { get; set; }
        public string DomicilioCalle { get; set; }
        public string DomicilioNumero { get; set; }
        public string DomicilioManzana { get; set; }
        public string DomicilioPiso { get; set; }
        public string DomicilioDepto { get; set; }
        public string CalleReferencia1 { get; set; }
        public string CalleReferencia2 { get; set; }
        public Nullable<int> BarrioID { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoCelular { get; set; }
        public string Email { get; set; }
        public Nullable<int> LocalidadNacimientoID { get; set; }
        public Nullable<int> NacionalidadID { get; set; }
        public string CUIL { get; set; }
        public bool Fallecido { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaFallecido { get; set; }
        public string DomicilioLaboralCalle { get; set; }
        public string DomicilioLaboralNumero { get; set; }
        public string DomicilioLaboralManzana { get; set; }
        public string DomicilioLaboralPiso { get; set; }
        public string DomicilioLaboralDepto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual TipoDNI TipoDNI { get; set; }
        public virtual TipoEstadoCivil TipoEstadoCivil { get; set; }
        public virtual TipoSexo TipoSexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profesional> Profesional { get; set; }
    }
}
